[package]
name = "kuhn_poker_ai"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
peroxide = { version = "0.34.0", features = ["parquet"] }
rand = "0.8.5"
